### ISSUE TITLE
Indent markers not visible in JSON files with NeoVim v0.2.0 on Mac OS 10.11.6

### ISSUE THREAD

**Issue by AdrianTP** [Yggdroot/indentLine#233]
As the title says, I have indent markers in seemingly every file type except for JSON.

Ruby code with indent markers:
![image](https://user-images.githubusercontent.com/1585276/35699305-463c819c-0755-11e8-974a-eba59e97d483.png)

JSON file with no markers:
![image](https://user-images.githubusercontent.com/1585276/35699345-62d0b594-0755-11e8-8b6b-7fe99dd858a5.png)

Relevant section from my init.vim:
```vim
if has("gui_running")
  if has("gui_mac") || has("gui_macvim")
    set guifont=Menlo:h12
    set transparency=7
  endif
else
  let g:CSApprox_loaded = 1

  " IndentLine
  let g:indentLine_enabled = 1
  let g:indentLine_concealcursor = 0
  let g:indentLine_char = '┆'
  let g:indentLine_faster = 1

  
endif
```

I could find no other helpful information in either of the other two tickets which address suspected issues with JSON files (https://github.com/Yggdroot/indentLine/issues/140 and https://github.com/Yggdroot/indentLine/issues/231)

**Comment by Yggdroot** [comment]
Have you tried this:

This issue is because the author of json's [syntax file](https://github.com/vim/vim/blob/master/runtime/syntax/json.vim) thought people like the quotes being concealed.
To fix the issue, you can do like this:
1. enter vim
2. `:e $VIMRUNTIME/syntax/json.vim`
3. `:g/if has('conceal')/s//& \&\& 0/`
4. `:wq`

**Comment by Yggdroot** [comment]
You should refer to issue #59 , not 140 or 231.
