### ISSUE TITLE
The default configuration of g:indentLine_noConcealCursor is conflict with vimwiki

### ISSUE THREAD

**Issue by wweir** [Yggdroot/indentLine#65]
Sometimes I use sublime text, I love indexLine very much.

Today, I open the vimwiki to write my blog, but it does not work as usual. 

After a long time test, I find the default configuration g:indentLine_noConcealCursor in indexLine lead to this, which **set concealcursor=inc** in my Vim without any warning.

**Comment by Datamance** [comment]
@Yggdroot this issue is certainly not fixed, in particular with the latest version of indentLine at 15aceda8c4eea621b66faa8673fca0b9fbe2f457 and vimwiki at vimwiki/vimwiki@64c9f3d36d632b1657616c06ea8f08f14cf6438d (master).

The only solution that works is referenced [here](https://github.com/plasticboy/vim-markdown/issues/395#issuecomment-436719952). Setting `_setConceal` and/or `_fileTypeExclude` do nothing to remediate the problem.
